hello: hello,prod

quarkus:
  redis:
    hosts: redis://aliyun-prod:6379
    password: 'abc123'
  datasource:
    db-kind: postgresql
    username: postgres
    password: z1l78fkSMgq8o0
    jdbc:
      driver: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:postgresql://aliyun-tmp:5432/db_pg_eladmin
  hibernate-orm:
    log:
      # the printed sql is containing ?
      sql: false
  smallrye-openapi:
    enable: false

