quarkus:
  application:
    name: eladmin
  profile: dev
  http:
    # 不配置host，只能 localhost 访问
    # 因为 前端页面是在另一个服务器上（使用vscode + remote development），要访问本服务
    host: 0.0.0.0
    #    port: 20008
    port: 8000
    #    root-path: "/api"
    limits:
      max-body-size: 12M
  # https://quarkus.io/guides/datasource
  datasource:
    db-kind: postgresql
    username: postgres
    password: z1l78fkSMgq8o0
    jdbc:
      driver: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:postgresql://aliyuntest:5432/db_pg_eladmin
      max-size: 5
      min-size: 1
  # https://quarkus.io/guides/hibernate-orm
  hibernate-orm:
    #    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
    implicit-naming-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    # https://docs.jboss.org/hibernate/orm/6.6/dialect/dialect.html
    #    dialect: MySQL
    #    dialect: cn.valuetodays.api3.web.extend.NoEscapeMySQLDialect
    schema-management:
      strategy: none
    packages: me.zhengjie
    database:
      #      generation: none
      version-check:
        enabled: false
    sql-load-script: no-file
    log:
      # the printed sql is containing ?
      sql: false
    validate-in-dev: false
    validation:
      mode: none
  package:
    jar:
      type: UBER_JAR
    runner-suffix: -runner
  thread-pool:
    max-threads: 200
    core-threads: 20
    queue-size: 1000
  redis:
    hosts: redis://localhost:6379
    password: 'abc123'
    timeout: 10s
    database: 0
  log:
    debug: true
    level: INFO
    #    handlers: ["console", "file"]
    console:
      enable: true
    file:
      enable: true
      path: /root/workbench/logs/valuetodays-api3-by-quarkus/valuetodays-api3-by-quarkus.log
      rotation:
        #        rotate-on-boot: true # 是否按服务启动滚动
        max-file-size: 10M
        max-backup-index: 15
        file-suffix: .yyyy-MM-dd
  smallrye-openapi:
    enable: true

login:
  #  是否限制单用户登录
  single-login: false
  # Redis用户登录缓存配置   # 存活时间/秒
  user-cache-idle-time: 21600
  #  验证码
  captcha:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: ARITHMETIC
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name: ''
    # 字体大小
    font-size: 25

# 亚马逊S3协议云存储配置
#支持七牛云，阿里云OSS，腾讯云COS，华为云OBS，移动云EOS等
amz:
  s3:
    # 地域
    region: test
    # 地域对应的 endpoint
    end-point: https://s3.test.com
    # 访问的域名
    domain: https://s3.test.com
    # 账号的认证信息，或者子账号的认证信息
    access-key: 填写你的AccessKey
    secret-key: 填写你的SecretKey
    # 存储桶（Bucket）
    default-bucket: 填写你的存储桶名称
    # 文件存储路径
    timeformat: yyyy-MM

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true
  base-path: /tmp/eladmin_gen

# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/eladmin/file/
    avatar: /home/eladmin/avatar/
  windows:
    path: C:\eladmin\file\
    avatar: C:\eladmin\avatar\
  # 文件大小 /M
  max-size: 100
  avatar-max-size: 2

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private-key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==
