CREATE TABLE if not exists "basic_vt_server"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(64) NOT NULL,
    "port_bindings" varchar(256) NOT NULL,
    "time_zone_enabled" int NOT NULL,
    "domain" varchar(64) NOT NULL,
    "https_enabled" int NOT NULL,
    "image_name" varchar(64) NOT NULL,
    "enabled" int NOT NULL,
    "create_by" varchar(64) NOT NULL,
    "update_by" varchar(64) NOT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "basic_vt_server" IS 'vt服务';
COMMENT ON COLUMN "basic_vt_server"."id" IS 'ID';
COMMENT ON COLUMN "basic_vt_server"."name" IS '名称';
COMMENT ON COLUMN "basic_vt_server"."port_bindings" IS '绑定的端口，外网->内网';
COMMENT ON COLUMN "basic_vt_server"."time_zone_enabled" IS 'timezone状态：1启用、0禁用';
COMMENT ON COLUMN "basic_vt_server"."domain" IS '域名';
COMMENT ON COLUMN "basic_vt_server"."https_enabled" IS 'https状态：1启用、0禁用';
COMMENT ON COLUMN "basic_vt_server"."image_name" IS '镜像地址';
COMMENT ON COLUMN "basic_vt_server"."enabled" IS '状态：1启用、0禁用';
COMMENT ON COLUMN "basic_vt_server"."create_by" IS '创建者';
COMMENT ON COLUMN "basic_vt_server"."update_by" IS '更新者';
COMMENT ON COLUMN "basic_vt_server"."create_time" IS '创建日期';
COMMENT ON COLUMN "basic_vt_server"."update_time" IS '更新时间';

-- 主键
alter table "basic_vt_server"
add constraint pk_basic_vt_server primary key ("id");

CREATE TABLE if not exists "nation_code"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(255) NULL,
    "alpha_3_code" varchar(255) NULL,
    "numeric" varchar(32) NULL,
    "english_name" varchar(255) NULL,
    "chinese_name" varchar(255) NULL,
    "symbol" varchar(255) NULL,
    "currency" varchar(255) NULL,
    "phone_area_code" varchar(255) NULL,
    "flag" varchar(255) NULL,
    "enabled" int NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "nation_code" IS '国家列表和区号列表';
COMMENT ON COLUMN "nation_code"."code" IS '国家编码2位';
COMMENT ON COLUMN "nation_code"."alpha_3_code" IS '国家编码3位';
COMMENT ON COLUMN "nation_code"."numeric" IS '国家数字编码';
COMMENT ON COLUMN "nation_code"."english_name" IS '国家名称（英文）';
COMMENT ON COLUMN "nation_code"."chinese_name" IS '国家名称（中文）';
COMMENT ON COLUMN "nation_code"."symbol" IS '货币符号';
COMMENT ON COLUMN "nation_code"."currency" IS '货币';
COMMENT ON COLUMN "nation_code"."phone_area_code" IS '手机区号';
COMMENT ON COLUMN "nation_code"."flag" IS '国旗';
COMMENT ON COLUMN "nation_code"."enabled" IS '状态：1启用、0禁用';

-- 主键
alter table "nation_code"
add constraint pk_nation_code primary key ("id");

