<?xml version="1.0" encoding="UTF-8"?>
<project
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>me.vt</groupId>
        <artifactId>portal</artifactId>
        <version>v2025-12-01</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>portal-generator</artifactId>

    <properties>
        <configuration.version>1.10</configuration.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>me.vt</groupId>
            <artifactId>portal-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/commons-configuration/commons-configuration -->
        <dependency>
            <groupId>commons-configuration</groupId>
            <artifactId>commons-configuration</artifactId>
            <version>${configuration.version}</version>
        </dependency>
    </dependencies>
</project>
