<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>me.vt</groupId>
        <artifactId>portal</artifactId>
        <version>v2025-12-01</version>
    </parent>

    <artifactId>module-mybiz</artifactId>

    <dependencies>
        <dependency>
            <groupId>me.vt</groupId>
            <artifactId>module-mybiz-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.vt</groupId>
            <artifactId>portal-tools</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.vt</groupId>
            <artifactId>portal-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.vt.api2</groupId>
            <artifactId>module-stock-trade</artifactId>
            <version>${vt.api2.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>api2-client</artifactId>
                    <groupId>com.vt.api2</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>common-web</artifactId>
                    <groupId>com.vt.commons</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.ta4j</groupId>
            <artifactId>ta4j-core</artifactId>
            <version>0.18</version>
        </dependency>
    </dependencies>
</project>
